name: iboxpro_flutter
description: Flutter плагин для работы с библиотекой iboxpro
version: 0.1.0
author: Unact <it@unact.ru>
homepage: https://github.com/Unact/iboxpro_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.unact.iboxpro_flutter
    pluginClass: IboxproFlutterPlugin
